fix(cfg): `Cfg*::*_define` now requires `Bag` with inherited constness (`~const`)
Because otherwise you can't use the given `Bag` at all in the trait
implementations!

    error[E0015]: calls in constant functions are limited to constant functions, tuple structs and tuple variants
      --> src/r3_kernel/src/cfg/task.rs:28:29
       |
    28 |         if let Some(hunk) = properties.get::<StackHunk<Self::System>>() {
       |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

It's unknown why `impl Trait` doesn't seem to support `~const`.