fix(core): add missing bounds to type-alias-impl-traits
It seems that [rust-lang/rust#96736][1] introduced checks for these
missing bounds, resulting in the following compilation error:

     error[E0277]: expected a `FnOnce<(Output,)>` closure, found `Mapper`
         --> src/r3_core/src/bind.rs:1360:5
          |
     1360 |     move || (mapper)(inner_bound_fn())
          |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected an `FnOnce<(Output,)>` closure, found `Mapper`
          |
     note: required by a bound in `map_bind_inner`
         --> src/r3_core/src/bind.rs:1358:13
          |
     1352 | const fn map_bind_inner<InnerBoundFn, Output, Mapper, NewOutput>(
          |          -------------- required by a bound in this
     ...
     1358 |     Mapper: FnOnce(Output) -> NewOutput + Copy + Send + 'static,
          |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `map_bind_inner`
     help: consider further restricting this bound
          |
     1349 |     Mapper: Copy + Send + 'static + core::ops::FnOnce<(Output,)>,
          |                                   ++++++++++++++++++++++++++++++

[1]: https://github.com/rust-lang/rust/pull/96736