chore(ci): temporarily disable the documentation generation of `r3_support_rp2040`
Building a documentation for `rp2040` currently causes a compiler crash.
This is probably related to [rust-lang/rust#93476][1].

    thread 'rustc' panicked at 'no entry found for key', src/librustdoc/passes/collect_intra_doc_links.rs:930:16

[1]: https://github.com/rust-lang/rust/issues/93476